fixed and updated photogrammetry script and dockerfile

diff --git a/photogrammetry b/photogrammetry
--- a/photogrammetry
+++ b/photogrammetry
@@ -5,7 +5,7 @@
 #          This script starts the photogrammetry pipeline inside the meshroom docker container
 # ------------------------------------------------------------------
 
-VERSION=0.1.0
+VERSION=0.2
 SUBJECT=some-unique-id
 USAGE="Usage: photogrammetry input_folder_name"
 
@@ -65,8 +65,25 @@ echo $param1
 echo $param2
 #TODO add image compression
 #TODO use custom graph file
-/opt/Meshroom/meshroom_batch --input /data/img_in/"$param1" --output /data/model/"$param1" -p photogrammetry >> /data/log/meshroom_output
+if [ ! -f /data/log/meshroom_output ]; then
+    touch /data/log/meshroom_output
+fi
+if [ ! -d /data/model/"$param1" ]; then
+    mkdir /data/model/"$param1"
+fi
+if [ ! -f /data/log/obj2gltf_output ]; then
+    touch /data/log/obj2gltf_output
+fi
+/opt/Meshroom/meshroom_batch --input /data/img_in/"$param1" --output /data/model/"$param1"/ -p photogrammetry >> /data/log/meshroom_output
+#BACK_PID=$!
+#wait $BACK_PID
 #TODO copy logfiles to log volume
-obj2gltf -b -i /data/img_in/"$param1"/texturedMesh.obj -o /data/model/"$param1"/model.glb >> obj2gltf_output
+
+if [ -f /data/model/"$param1"/texturedMesh.obj ] ; then
+  obj2gltf -b -i /data/model/"$param1"/texturedMesh.obj -o /data/model/"$param1"/model.glb >> obj2gltf_output
+else
+  >&2 echo "Error: Couldn't find 3D Model. Probably, Meshroom failed while calculating the model. Check if enough ressources are available. Check Meshroom log."
+fi
+
 
 # -----------------------------------------------------------------
